plugins { id 'com.android.application' }

android {
    namespace 'com.ether404.retrospace'
    compileSdk 36
    defaultConfig {
        applicationId 'com.ether404.retrospace'
        minSdk 28
        targetSdk 36
        versionCode 1
        versionName '0.1.0'
    }
}

dependencies { implementation 'androidx.core:core:1.17.0' }
